### ISSUE TITLE
Reboot

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/amemo#64]
Just tried to run this on `localhost` and got the following error:

```sh
 mix setup
warning: use Mix.Config is deprecated. Use the Config module instead
  config/config.exs:8

warning: Mix.Config.config/2 is deprecated. Use the Config module instead
  config/config.exs:10

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/config.exs:14

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/config.exs:22

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/config.exs:27

warning: Mix.Config.import_config/1 is deprecated. Use the Config module instead
  config/config.exs:31

warning: use Mix.Config is deprecated. Use the Config module instead
  config/dev.exs:1

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/dev.exs:4

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/dev.exs:18

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/dev.exs:58

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/dev.exs:69

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/dev.exs:73

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/dev.exs:76

Resolving Hex dependencies...
Resolution completed in 0.055s
Unchanged:
  connection 1.0.4
  cowboy 2.8.0
  cowlib 2.9.1
  db_connection 2.2.2
  decimal 1.8.1
  ecto 3.4.4
  ecto_sql 3.4.4
  file_system 0.2.8
  gettext 0.18.0
  jason 1.2.1
  mime 1.3.1
  phoenix 1.5.3
  phoenix_ecto 4.1.0
  phoenix_html 2.14.2
  phoenix_live_dashboard 0.2.6
  phoenix_live_reload 1.2.2
  phoenix_live_view 0.13.3
  phoenix_pubsub 2.0.0
  plug 1.10.2
  plug_cowboy 2.2.2 RETIRED!
    (invalid) Broken telemetry support
  plug_crypto 1.1.2
  postgrex 0.15.5
  ranch 1.7.1
  telemetry 0.4.1
  telemetry_metrics 0.5.0
  telemetry_poller 0.5.0
All dependencies are up to date
==> ecto
Compiling 55 files (.ex)
warning: missing parentheses for expression following "do:" keyword. Parentheses are required to solve ambiguity inside keywords.

This error happens when you have function calls without parentheses inside keywords. For example:

    function(arg, one: nested_call a, b, c)
    function(arg, one: if expr, do: :this, else: :that)

In the examples above, we don't know if the arguments "b" and "c" apply to the function "function" or "nested_call". Or if the keywords "do" and "else" apply to the function "function" or "if". You can solve this by explicitly adding parentheses:

    function(arg, one: if(expr, do: :this, else: :that))
    function(arg, one: nested_call(a, b, c))

Ambiguity found at:
  lib/ecto/association.ex:381

warning: missing parentheses for expression following "do:" keyword. Parentheses are required to solve ambiguity inside keywords.

This error happens when you have function calls without parentheses inside keywords. For example:

    function(arg, one: nested_call a, b, c)
    function(arg, one: if expr, do: :this, else: :that)

In the examples above, we don't know if the arguments "b" and "c" apply to the function "function" or "nested_call". Or if the keywords "do" and "else" apply to the function "function" or "if". You can solve this by explicitly adding parentheses:

    function(arg, one: if(expr, do: :this, else: :that))
    function(arg, one: nested_call(a, b, c))

Ambiguity found at:
  lib/ecto/changeset.ex:560

warning: missing parentheses for expression following "do:" keyword. Parentheses are required to solve ambiguity inside keywords.

This error happens when you have function calls without parentheses inside keywords. For example:

    function(arg, one: nested_call a, b, c)
    function(arg, one: if expr, do: :this, else: :that)

In the examples above, we don't know if the arguments "b" and "c" apply to the function "function" or "nested_call". Or if the keywords "do" and "else" apply to the function "function" or "if". You can solve this by explicitly adding parentheses:

    function(arg, one: if(expr, do: :this, else: :that))
    function(arg, one: nested_call(a, b, c))

Ambiguity found at:
  lib/ecto/changeset.ex:2803

warning: missing parentheses for expression following "do:" keyword. Parentheses are required to solve ambiguity inside keywords.

This error happens when you have function calls without parentheses inside keywords. For example:

    function(arg, one: nested_call a, b, c)
    function(arg, one: if expr, do: :this, else: :that)

In the examples above, we don't know if the arguments "b" and "c" apply to the function "function" or "nested_call". Or if the keywords "do" and "else" apply to the function "function" or "if". You can solve this by explicitly adding parentheses:

    function(arg, one: if(expr, do: :this, else: :that))
    function(arg, one: nested_call(a, b, c))

Ambiguity found at:
  lib/ecto/changeset.ex:2805

warning: atom ::: must be written between quotes, as in :"::", to avoid ambiguity
  lib/ecto/query/builder.ex:246:8

warning: unknown compiler variable "__" (expected one of __MODULE__, __ENV__, __DIR__, __CALLER__, __STACKTRACE__)
  lib/ecto/query/builder.ex:980: Ecto.Query.Builder.quoted_type/2

warning: unknown compiler variable "__" (expected one of __MODULE__, __ENV__, __DIR__, __CALLER__, __STACKTRACE__)
  lib/ecto/query/builder.ex:981: Ecto.Query.Builder.quoted_type/2

warning: missing parentheses for expression following "do:" keyword. Parentheses are required to solve ambiguity inside keywords.

This error happens when you have function calls without parentheses inside keywords. For example:

    function(arg, one: nested_call a, b, c)
    function(arg, one: if expr, do: :this, else: :that)

In the examples above, we don't know if the arguments "b" and "c" apply to the function "function" or "nested_call". Or if the keywords "do" and "else" apply to the function "function" or "if". You can solve this by explicitly adding parentheses:

    function(arg, one: if(expr, do: :this, else: :that))
    function(arg, one: nested_call(a, b, c))

Ambiguity found at:
  lib/ecto/repo/schema.ex:526


== Compilation error in file lib/ecto/query.ex ==
** (Kernel.TypespecError) lib/ecto/query.ex:418: type dynamic/0 is a built-in type and it cannot be redefined
    (elixir 1.15.4) lib/kernel/typespec.ex:961: Kernel.Typespec.compile_error/2
    (stdlib 5.0.2) lists.erl:1599: :lists.foldl_1/3
    (elixir 1.15.4) lib/kernel/typespec.ex:226: Kernel.Typespec.translate_typespecs_for_module/2
could not compile dependency :ecto, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ecto --force", update it with "mix deps.update ecto" or clean it with "mix deps.clean ecto"
n@mbp16 amemo % git rm -r lib priv
n@mbp16 amemo % code .
n@mbp16 amemo % mix deps.clean ecto
warning: use Mix.Config is deprecated. Use the Config module instead
  config/config.exs:8

warning: Mix.Config.config/2 is deprecated. Use the Config module instead
  config/config.exs:10

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/config.exs:14

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/config.exs:22

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/config.exs:27

warning: Mix.Config.import_config/1 is deprecated. Use the Config module instead
  config/config.exs:31

warning: use Mix.Config is deprecated. Use the Config module instead
  config/dev.exs:1

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/dev.exs:4

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/dev.exs:18

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/dev.exs:58

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/dev.exs:69

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/dev.exs:73

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/dev.exs:76

* Cleaning ecto
n@mbp16 amemo % mix setup
warning: use Mix.Config is deprecated. Use the Config module instead
  config/config.exs:8

warning: Mix.Config.config/2 is deprecated. Use the Config module instead
  config/config.exs:10

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/config.exs:14

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/config.exs:22

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/config.exs:27

warning: Mix.Config.import_config/1 is deprecated. Use the Config module instead
  config/config.exs:31

warning: use Mix.Config is deprecated. Use the Config module instead
  config/dev.exs:1

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/dev.exs:4

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/dev.exs:18

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/dev.exs:58

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/dev.exs:69

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/dev.exs:73

warning: Mix.Config.config/3 is deprecated. Use the Config module instead
  config/dev.exs:76

Resolving Hex dependencies...
Resolution completed in 0.052s
Unchanged:
  connection 1.0.4
  cowboy 2.8.0
  cowlib 2.9.1
  db_connection 2.2.2
  decimal 1.8.1
  ecto 3.4.4
  ecto_sql 3.4.4
  file_system 0.2.8
  gettext 0.18.0
  jason 1.2.1
  mime 1.3.1
  phoenix 1.5.3
  phoenix_ecto 4.1.0
  phoenix_html 2.14.2
  phoenix_live_dashboard 0.2.6
  phoenix_live_reload 1.2.2
  phoenix_live_view 0.13.3
  phoenix_pubsub 2.0.0
  plug 1.10.2
  plug_cowboy 2.2.2 RETIRED!
    (invalid) Broken telemetry support
  plug_crypto 1.1.2
  postgrex 0.15.5
  ranch 1.7.1
  telemetry 0.4.1
  telemetry_metrics 0.5.0
  telemetry_poller 0.5.0
* Getting ecto (Hex package)
==> ecto
Compiling 55 files (.ex)
warning: missing parentheses for expression following "do:" keyword. Parentheses are required to solve ambiguity inside keywords.

This error happens when you have function calls without parentheses inside keywords. For example:

    function(arg, one: nested_call a, b, c)
    function(arg, one: if expr, do: :this, else: :that)

In the examples above, we don't know if the arguments "b" and "c" apply to the function "function" or "nested_call". Or if the keywords "do" and "else" apply to the function "function" or "if". You can solve this by explicitly adding parentheses:

    function(arg, one: if(expr, do: :this, else: :that))
    function(arg, one: nested_call(a, b, c))

Ambiguity found at:
  lib/ecto/association.ex:381

warning: missing parentheses for expression following "do:" keyword. Parentheses are required to solve ambiguity inside keywords.

This error happens when you have function calls without parentheses inside keywords. For example:

    function(arg, one: nested_call a, b, c)
    function(arg, one: if expr, do: :this, else: :that)

In the examples above, we don't know if the arguments "b" and "c" apply to the function "function" or "nested_call". Or if the keywords "do" and "else" apply to the function "function" or "if". You can solve this by explicitly adding parentheses:

    function(arg, one: if(expr, do: :this, else: :that))
    function(arg, one: nested_call(a, b, c))

Ambiguity found at:
  lib/ecto/changeset.ex:560

warning: missing parentheses for expression following "do:" keyword. Parentheses are required to solve ambiguity inside keywords.

This error happens when you have function calls without parentheses inside keywords. For example:

    function(arg, one: nested_call a, b, c)
    function(arg, one: if expr, do: :this, else: :that)

In the examples above, we don't know if the arguments "b" and "c" apply to the function "function" or "nested_call". Or if the keywords "do" and "else" apply to the function "function" or "if". You can solve this by explicitly adding parentheses:

    function(arg, one: if(expr, do: :this, else: :that))
    function(arg, one: nested_call(a, b, c))

Ambiguity found at:
  lib/ecto/changeset.ex:2803

warning: missing parentheses for expression following "do:" keyword. Parentheses are required to solve ambiguity inside keywords.

This error happens when you have function calls without parentheses inside keywords. For example:

    function(arg, one: nested_call a, b, c)
    function(arg, one: if expr, do: :this, else: :that)

In the examples above, we don't know if the arguments "b" and "c" apply to the function "function" or "nested_call". Or if the keywords "do" and "else" apply to the function "function" or "if". You can solve this by explicitly adding parentheses:

    function(arg, one: if(expr, do: :this, else: :that))
    function(arg, one: nested_call(a, b, c))

Ambiguity found at:
  lib/ecto/changeset.ex:2805

warning: atom ::: must be written between quotes, as in :"::", to avoid ambiguity
  lib/ecto/query/builder.ex:246:8

warning: unknown compiler variable "__" (expected one of __MODULE__, __ENV__, __DIR__, __CALLER__, __STACKTRACE__)
  lib/ecto/query/builder.ex:980: Ecto.Query.Builder.quoted_type/2

warning: unknown compiler variable "__" (expected one of __MODULE__, __ENV__, __DIR__, __CALLER__, __STACKTRACE__)
  lib/ecto/query/builder.ex:981: Ecto.Query.Builder.quoted_type/2

warning: missing parentheses for expression following "do:" keyword. Parentheses are required to solve ambiguity inside keywords.

This error happens when you have function calls without parentheses inside keywords. For example:

    function(arg, one: nested_call a, b, c)
    function(arg, one: if expr, do: :this, else: :that)

In the examples above, we don't know if the arguments "b" and "c" apply to the function "function" or "nested_call". Or if the keywords "do" and "else" apply to the function "function" or "if". You can solve this by explicitly adding parentheses:

    function(arg, one: if(expr, do: :this, else: :that))
    function(arg, one: nested_call(a, b, c))

Ambiguity found at:
  lib/ecto/repo/schema.ex:526


== Compilation error in file lib/ecto/query.ex ==
** (Kernel.TypespecError) lib/ecto/query.ex:418: type dynamic/0 is a built-in type and it cannot be redefined
    (elixir 1.15.4) lib/kernel/typespec.ex:961: Kernel.Typespec.compile_error/2
    (stdlib 5.0.2) lists.erl:1599: :lists.foldl_1/3
    (elixir 1.15.4) lib/kernel/typespec.ex:226: Kernel.Typespec.translate_typespecs_for_module/2
could not compile dependency :ecto, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ecto --force", update it with "mix deps.update ecto" or clean it with "mix deps.clean ecto"
```

Too many warnings and an unrecoverable error. 🤦‍♂️ 

This is the `JS` code: https://github.com/nelsonic/amemo/blob/8ecba2a2ead0ae7c7e1fc39142cd1d5549178c24/assets/js/app.js

**Comment by nelsonic** [comment]
This is interesting: https://alchemist.camp/episodes/phoenix-markdown-show-notes
But it's from 3 years ago and the code no longer works. So using it as a reference ... 💭

**Comment by nelsonic** [comment]
Rendering Markdown:
![image](https://github.com/nelsonic/amemo/assets/194400/e2056fad-d733-4bfb-9132-c8e3b73257ac)

Code:

```elixir
  def render(assigns) do
    md = """
    ## Hello World!

    This is my text
    [link](https://mvp.fly.dev/)
    https://mvp.fly.dev/
    """
    assigns = assign(assigns, :md, md)

    ~H"""
    <div class="markdown">
    <%= Phoenix.HTML.raw(to_html(@md)) %>

    <h1 class="text-4xl font-bold text-center"> The count is: <%= @val %> </h1>
     <.button phx-click="dec">-</.button>
     <.button phx-click="inc">+</.button>
     </div>
    """
  end

  def to_html(markdown) do
    markdown
    |> Earmark.as_html!()
    |> HtmlSanitizeEx.html5()
  end
```

**Comment by nelsonic** [comment]
Getting the following error:

```
[error] GenServer #PID<0.2473.0> terminating
** (FunctionClauseError) no function clause matching in Phoenix.Component.update/3
    (phoenix_live_view 0.19.5) lib/phoenix_component.ex:1298: Phoenix.Component.update(#Phoenix.LiveView.Socket<id: "phx-F3bi4KUpTrb5WwzB", endpoint: AmemoWeb.Endpoint, view: AmemoWeb.Editor, parent_pid: nil, root_pid: #PID<0.2473.0>, router: AmemoWeb.Router, assigns: %{val: 0, __changed__: %{}, flash: %{}, md: "## Hello World!\n\nThis is my text\n[link](https://mvp.fly.dev/)\nhttps://mvp.fly.dev/\n", live_action: nil}, transport_pid: #PID<0.2465.0>, ...>, :md, "## Hello World! Again\n\nThis is my text\n[link](https://mvp.fly.dev/)\nhttps://mvp.fly.dev/\n\n  ")
    (amemo 0.1.0) lib/amemo_web/live/editor.ex:17: AmemoWeb.Editor.handle_event/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:401: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 1.2.1) /Users/n/code/amemo/amemo/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:221: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F3bi4KUpTrb5WwzB", event: "event", payload: %{"event" => "render", "type" => "form", "uploads" => %{}, "value" => "text=%23%23+Hello+World%21+Again%0A%0AThis+is+my+text%0A%5Blink%5D%28https%3A%2F%2Fmvp.fly.dev%2F%29%0Ahttps%3A%2F%2Fmvp.fly.dev%2F%0A%0A++&_target=text"}, ref: "8", join_ref: "4"}
State: %{socket: #Phoenix.LiveView.Socket<id: "phx-F3bi4KUpTrb5WwzB", endpoint: AmemoWeb.Endpoint, view: AmemoWeb.Editor, parent_pid: nil, root_pid: #PID<0.2473.0>, router: AmemoWeb.Router, assigns: %{val: 0, __changed__: %{}, flash: %{}, md: "## Hello World!\n\nThis is my text\n[link](https://mvp.fly.dev/)\nhttps://mvp.fly.dev/\n", live_action: nil}, transport_pid: #PID<0.2465.0>, ...>, components: {%{}, %{}, 1}, topic: "lv:phx-F3bi4KUpTrb5WwzB", serializer: Phoenix.Socket.V2.JSONSerializer, join_ref: "4", upload_names: %{}, upload_pids: %{}}
[debug] MOUNT AmemoWeb.Editor
```

**Comment by nelsonic** [comment]
![amemo-localhost](https://github.com/nelsonic/amemo/assets/194400/17400372-0722-4fa7-ab38-1dfd806cd530)
